language: go

go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo
  - echo "blog.mneundorfer.de" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  repo: mneund/mneund.github.io
  target_branch: master
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master